---
- name: create virtual machines
  proxmox_kvm:
    api_host: "{{ proxmox_api_host }}"
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    node: "{{ item.node }}"
    clone: "{{ item.template }}"
    newid: "{{ item.vmid }}"
    name: "{{ item.name }}"
    timeout: 300
  loop: "{{ proxmox_vms }}"

- name: update virtual machines parameters
  proxmox_kvm:
    api_host: "{{ proxmox_api_host }}"
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    node: "{{ item.node | default(proxmox_vm_default.node) }}"
    vmid: "{{ item.vmid }}"
    sockets: "{{ item.sockets | default(proxmox_vm_default.sockets) }}"
    cores: "{{ item.cores | default(proxmox_vm_default.cores) }}"
    memory: "{{ item.memory | default(proxmox_vm_default.memory) }}"
    onboot: "{{ item.onboot | default(proxmox_vm_default.onboot) }}"
    agent: "{{ item.agent | default(proxmox_vm_default.agent) }}"
    balloon: "{{ item.balloon | default(proxmox_vm_default.balloon) }}"
    description: "{{ item.description | default(omit) }}"
    update: yes
  loop: "{{ proxmox_vms }}"
  changed_when: no

- name: copy ssh key to temporary file
  copy:
    content: "{{ item.ssh_key }}"
    dest: "/tmp/{{ item.vmid }}.pub"
  loop: "{{ proxmox_vms }}"
  when:
    - item.vmid
    - item.ssh_key is defined

- name: configure cloud-init parameters
  include_tasks: cloud_init.yml

- name: start virtual machines
  proxmox_kvm:
    api_host: "{{ proxmox_api_host }}"
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    node: "{{ item.node | default(proxmox_vm_default.node) }}"
    vmid: "{{ item.vmid }}"
    state: started
  loop: "{{ proxmox_vms }}"

- name: wait for virtual machines to turn on
  wait_for:
    port: 22
    host: "{{ item.ip.split('/') | first }}"
    delay: 10
  loop: "{{ proxmox_vms }}"
  when: item.ip is defined
